"use client"
import { Inter } from "next/font/google";
import { useEffect } from "react";
import Head from "next/head";
import Navbar from "./Components/Navbar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Illford technologies",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }) => {
  const path = usePathname()

  useEffect(() => {
    const dynamicMetadata = {
      '/': {
        title: 'The Best Web Development Services Kochi | Web Designing Services Kochi - Illford Technologies',
        description: 'Revolutionize your digital sphere with Illford Technologies - The best Web Development Services Kochi, Web designing experts in Kochi and Digital marketing experts in Kochi. Express your digital identity through innovation and excellence',
        keywords: 'Web development experts in Kochi, Web designing experts in Kochi, App development company in Kochi, Web development company in Kochi, Web development experts in Kochi, Digital marketing experts in Kochi, Best website development company in Kochi, Web design services Kochi, Website development services Kerala, Website design services Kerala',
        language: 'english',
        rating: 'General',
        robots: 'follow,index',
        canonical: 'https://illfordtechnologies.com/',
        dcTitle: 'The Best Web Development Services Kochi | Web Designing Services Kochi - Illford Technologies',
        geoRegion: 'IN-KL',
        geoPlacename: 'Kochi',
        geoPosition: '9.967428;76.245444',
        icbm: '9.967428, 76.245444',
        ogType: 'website',
        ogUrl: 'https://illfordtechnologies.com/',
        ogTitle: 'The Best Web Development Services Kochi | Web Designing Services Kochi - Illford Technologies',
        ogDescription: 'Revolutionize your digital sphere with Illford Technologies - The best Web Development Services Kochi, Web designing experts in Kochi and Digital marketing experts in Kochi. Express your digital identity through innovation and excellence',
        ogImage: 'https://illfordtechnologies.in/images/illford-logo.png',
        twitterCard: 'summary_large_image',
        twitterUrl: 'https://illfordtechnologies.com/',
        twitterTitle: 'The Best Web Development Services Kochi | Web Designing Services Kochi - Illford Technologies',
        twitterescription: 'Revolutionize your digital sphere with Illford Technologies - The best Web Development Services Kochi, Web designing experts in Kochi and Digital marketing experts in Kochi. Express your digital identity through innovation and excellence.',
        twitterImage: 'https://illfordtechnologies.in/images/illford-logo.png'
      },
      '/about': {
        title: 'About Illford Technologies | Web development company in Kochi and Web designing company in Kochi',
        description: 'Discover Illford Technologies, a top Website development company in Kochi and Website designing company in Kochi. For an excellent online experience, discover our proficiency in creative design, tactical digital marketing, and dependable server solutionsDiscover Illford Technologies, a top Website development company in Kochi and Website designing company in Kochi. For an excellent online experience, discover our proficiency in creative design, tactical digital marketing, and dependable server solutions..',
        keywords: 'Website development experts in Kochi, Website designing experts in Kochi, Website design services Kochi, Website development services Kochi, Web design services Kerala, Top website development company in Kochi, Digital marketing services in Kochi, Web development experts in Kerala, Website development company in Kochi, App development company in Kerala',
        language: 'english',
        rating: 'General',
        robots: 'follow,index',
        canonical: 'https://illfordtechnologies.in/about',
        dcTitle: 'About Illford Technologies | Web development company in Kochi and Web designing company in Kochi',
        geoRegion: 'IN-KL',
        geoPlacename: 'Kochi',
        geoPosition: '9.967428;76.245444',
        icbm: '9.967428, 76.245444',
        ogType: 'website',
        ogUrl: 'https://illfordtechnologies.in/about',
        ogTitle: 'The Best Web Development Services Kochi | Web Designing Services Kochi - Illford Technologies',
        ogDescription: 'Discover Illford Technologies, a top Website development company in Kochi and Website designing company in Kochi. For an excellent online experience, discover our proficiency in creative design, tactical digital marketing, and dependable server solutions',
        ogImage: '',
        twitterCard: 'summary_large_image',
        twitterUrl: 'https://illfordtechnologies.in/about',
        twitterTitle: 'The Best Web Development Services Kochi | Web Designing Services Kochi - Illford Technologies',
        twitterescription: 'Discover Illford Technologies, a top Website development company in Kochi and Website designing company in Kochi. For an excellent online experience, discover our proficiency in creative design, tactical digital marketing, and dependable server solutions.',
        twitterImage: ''
      },
      '/services': {
        title: 'Website Designing services Kochi and Website development services Ernakulam | Illford Technologies',
        description: 'Illford Technologies: Elevate your online presence with Web Design Company Kochi and Web Development Services Kochi. Our commitment extends to strategic marketing and reliable digital marketing services Kochi offering a holistic online experience.',
        keywords: 'Web Development Agency Kochi, Web Development Agency Kerala, Web Designing Agency Kochi, UI/UX Designing Kochi, Digital Marketing Specialist Kochi, Top Web Development Services Kochi, Web designing experts in Ernakulam, Digital Marketing Services in Kerala, Website  development experts in Kerala, App development company in Ernakulam',
        language: 'english',
        rating: 'General',
        robots: 'follow,index',
        canonical: 'https://illfordtechnologies.in/services',
        dcTitle: 'Website Designing services Kochi and Website development services Ernakulam | Illford Technologies',
        geoRegion: 'IN-KL',
        geoPlacename: 'Kochi',
        geoPosition: '9.967428;76.245444',
        icbm: '9.967428, 76.245444',
        ogType: 'website',
        ogUrl: 'https://illfordtechnologies.in/services',
        ogTitle: 'Website Designing services Kochi and Website development services Ernakulam | Illford Technologies',
        ogDescription: 'Illford Technologies: Elevate your online presence with Web Design Company Kochi and Web Development Services Kochi. Our commitment extends to strategic marketing and reliable digital marketing services Kochi offering a holistic online experience.',
        ogImage: '',
        twitterCard: 'summary_large_image',
        twitterUrl: 'https://illfordtechnologies.in/services',
        twitterTitle: 'Website Designing services Kochi and Website development services Ernakulam | Illford Technologies',
        twitterescription: 'Illford Technologies: Elevate your online presence with Web Design Company Kochi and Web Development Services Kochi. Our commitment extends to strategic marketing and reliable digital marketing services Kochi offering a holistic online experience.',
        twitterImage: ''
      },
      '/contact': {
        title: 'Contact Illford Technologies| Web Design Services Kochi and Web Development Services Kochi',
        description: 'Contact Illford Technologies for expert Web design services Kochi and Web Development Services Kochi. Evaluate reliable digital marketing services in Kochi to ensure a flawless online experience',
        keywords: 'Web Development Contact Kochi, Contact for Web Designing Company Kochi, Contact for UI/UX Designing  Kochi, Contact Web Development Firm Kerala, Contact for Web Development Services Kochi, Contact for Web Development Services Ernakulam, Web Designing Agency Kerala, Contact for Digital Marketing Solutions Kochi, Contact for Web Development Kochi, Contact for Web Designing services Kochi',
        language: 'english',
        rating: 'General',
        robots: 'follow,index',
        canonical: 'https://illfordtechnologies.in/contact',
        dcTitle: 'Contact Illford Technologies| Web Design Services Kochi and Web Development Services Kochi',
        geoRegion: 'IN-KL',
        geoPlacename: 'Kochi',
        geoPosition: '9.967428;76.245444',
        icbm: '9.967428, 76.245444',
        ogType: 'website',
        ogUrl: 'https://illfordtechnologies.in/contact',
        ogTitle: 'Contact Illford Technologies| Web Design Services Kochi and Web Development Services Kochi',
        ogDescription: 'Contact Illford Technologies for expert Web design services Kochi and Web Development Services Kochi. Evaluate reliable digital marketing services in Kochi to ensure a flawless online experience',
        ogImage: '',
        twitterCard: 'summary_large_image',
        twitterUrl: 'https://illfordtechnologies.in/contact',
        twitterTitle: 'Contact Illford Technologies| Web Design Services Kochi and Web Development Services Kochi',
        twitterescription: 'Contact Illford Technologies for expert Web design services Kochi and Web Development Services Kochi. Evaluate reliable digital marketing services in Kochi to ensure a flawless online experience.',
        twitterImage: ''
      },
    };
    const metadata = dynamicMetadata[path] || {};

    document.title = metadata.title || 'Default Title'; // Set document title
    let descriptionMetaTag = document.querySelector('meta[name="description"]');
    if (!descriptionMetaTag) {
      descriptionMetaTag = document.createElement('meta');
      descriptionMetaTag.setAttribute('name', 'description');
      document.head.appendChild(descriptionMetaTag);
    }
    descriptionMetaTag.setAttribute('content', metadata.description || 'Default Description'); // Set meta description

    const handleMetaTag = (name, content) => {
      let metaTag = document.querySelector(`meta[name="${name}"]`);
      if (!metaTag) {
        metaTag = document.createElement('meta');
        metaTag.setAttribute('name', name);
        document.head.appendChild(metaTag);
      }
      metaTag.setAttribute('content', content || '');
    };

    const handleCanonicalMetaTag = (rel, content) => {
      let metaTag = document.querySelector(`link[rel="${rel}"]`);
      if (!metaTag) {
        metaTag = document.createElement('link');
        metaTag.setAttribute('rel', rel);
        document.head.appendChild(metaTag);
      }
      metaTag.setAttribute('href', content || '');
    };

    handleMetaTag('keywords', metadata.keywords);
    handleMetaTag('language', metadata.language);
    handleMetaTag('rating', metadata.rating);
    handleMetaTag('robots', metadata.robots);
    handleCanonicalMetaTag('canonical', metadata.canonical);
    handleMetaTag('DC.title', metadata.dcTitle);
    handleMetaTag('geo.region', metadata.geoRegion);
    handleMetaTag('geo.placename', metadata.geoPlacename);
    handleMetaTag('geo.position', metadata.geoPosition);
    handleMetaTag('ICBM', metadata.icbm);
    handleMetaTag('og:type', metadata.ogType);
    handleMetaTag('og:url', metadata.ogUrl);
    handleMetaTag('og:Title', metadata.ogTitle);
    handleMetaTag('og:Description', metadata.ogDescription)
    handleMetaTag('og:image', metadata.ogImage);
    handleMetaTag('twitter:card', metadata.twitterCard);
    handleMetaTag('twitter:url', metadata.twitterUrl);
    handleMetaTag('twitter:title', metadata.twitterTitle);
    handleMetaTag('twitter:description', metadata.twitterescription);
    handleMetaTag('twitter:image', metadata.twitterImage);
  }, [path]);



  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Nunito+Sans:opsz@6..12&family=Poppins:ital,wght@0,100;0,200;0,400;0,500;0,600;0,700;0,800;1,300&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="" /> {/* Add an empty description meta tag */}


        {/* Add other meta tags */}

      </Head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );

};

export default RootLayout;
